// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvrnwhjiomtraaphfzmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cm53aGppb210cmFhcGhmem1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDQ1MDIsImV4cCI6MjA3MjkyMDUwMn0.tEwetva_s5EEbLuYHbCwy0lv4npRC7Ff1RwHY2SDhA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});